// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Metadata → Keywords*
 */
export interface MetadataDocumentDataKeywordsItem {
  /**
   * Keyword field in *Metadata → Keywords*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Keywords the search engine will use to index this website
   * - **API ID Path**: metadata.keywords[].keyword
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keyword: prismic.KeyTextField;
}

/**
 * Content for Metadata documents
 */
interface MetadataDocumentData {
  /**
   * Site Name field in *Metadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brand name (Tatz and Pirz Studio)
   * - **API ID Path**: metadata.site_name
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_name: prismic.KeyTextField;

  /**
   * Title field in *Metadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: This will be the name of the tab
   * - **API ID Path**: metadata.title
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Metadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A description of the site
   * - **API ID Path**: metadata.description
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Keywords field in *Metadata*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.keywords[]
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  keywords: prismic.GroupField<Simplify<MetadataDocumentDataKeywordsItem>>;

  /**
   * Opengraph Image field in *Metadata*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.opengraph_image
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  opengraph_image: prismic.ImageField<never>;

  /**
   * Opengraph Title field in *Metadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.opengraph_title
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  opengraph_title: prismic.KeyTextField;

  /**
   * Opengraph Description field in *Metadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.opengraph_description
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  opengraph_description: prismic.KeyTextField;
}

/**
 * Metadata document from Prismic
 *
 * - **API ID**: `metadata`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MetadataDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MetadataDocumentData>,
    "metadata",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument | MetadataDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      MetadataDocument,
      MetadataDocumentData,
      MetadataDocumentDataKeywordsItem,
      AllDocumentTypes,
    };
  }
}
